# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20161007_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activity',
            field=models.CharField(
                blank=True, max_length=200, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='module',
            field=models.CharField(
                choices=[
                    ('cinema', 'Cinema'), ('library', 'Library'),
                    ('digital', 'Multimedia')],
                max_length=20, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='partner',
            field=models.CharField(
                blank=True, max_length=200, verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='by',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, related_name='loans_made',
                to=settings.AUTH_USER_MODEL, verbose_name='by'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='specimen',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to='monitoring.Specimen',
                verbose_name='specimen'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, related_name='loans',
                to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='item',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, related_name='specimens',
                to='monitoring.StockItem', verbose_name='item'),
        ),
    ]
