# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


def set_physical(apps, schema_editor):
    StockItem = apps.get_model('monitoring', 'StockItem')

    db_alias = schema_editor.connection.alias

    items = StockItem.objects.all()

    for item in items:
        if any(s.instance.physical for s in item.specimens):
            item.physical = True
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_unique_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem', name='physical',
            field=models.BooleanField(default=False),
            preserve_default=False),
        migrations.RunPython(
            set_physical, reverse_code=migrations.RunPython.noop,
            hints={'using': 'default'}),
    ]
