# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


def set_physical(apps, schema_editor):
    StockItem = apps.get_model('monitoring', 'StockItem')
    BookSpecimen = apps.get_model('library', 'BookSpecimen')

    db_alias = schema_editor.connection.alias

    for item in StockItem.objects.using(db_alias).all():
        for specimen in item.specimens.all():
            # We can't use the `instance` property here, because this is not an
            # actual Specimen object, just a fake one for the migration
            try:
                # We also can't use the `physical` property here, for the same
                # reason
                physical = not specimen.bookspecimen.file

            except BookSpecimen.DoesNotExist:
                # This is not a BookSpecimen, and as such can only be physical
                physical = True

            if physical:
                item.physical = True
                item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_unique_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem', name='physical',
            field=models.BooleanField(default=False),
            preserve_default=False),
        migrations.RunPython(
            set_physical, reverse_code=migrations.RunPython.noop,
            hints={'using': 'default'}),
        migrations.AlterField(
            model_name='stockitem', name='physical',
            field=models.BooleanField(default=True)),
    ]
