# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0010_auto_20161007_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='package_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='package'),
        ),
    ]
