# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0011_auto_20161007_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='credits',
            field=models.CharField(max_length=300, verbose_name='Authorship'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original',
            field=models.FileField(help_text='Maximum size : 500 Mo.', max_length=10240, upload_to='mediacenter/document', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='preview',
            field=models.ImageField(blank=True, max_length=10240, upload_to='mediacenter/preview', verbose_name='Preview picture'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Topics'),
        ),
    ]
