# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0012_auto_20170210_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('image', 'image'), ('audio', 'sound'), ('video', 'video'), ('pdf', 'pdf'), ('text', 'text'), ('epub', 'epub'), ('mobi', 'mobi'), ('app', 'app'), ('other', 'other')], default='other', max_length=5, verbose_name='type'),
        ),
    ]
