# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import ideascube.search.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0014_escape_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
    ]
