# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ideascube.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideascube', '0004_auto_20160322_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('namespace', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=40)),
                ('value', ideascube.models.JSONField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
