# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 20:45
from __future__ import unicode_literals

from django.db import migrations
import ideascube.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ideascube', '0006_auto_20160726_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ku_level',
            field=ideascube.fields.CommaSeparatedCharField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Kurdish knowledge'),
        ),
    ]
