# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_settings_to_configuration'),
        ('ideascube', '0009_add_a_system_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='actor',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
