# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideascube', '0012_auto_20161013_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('no_profession', 'Without profession'), ('profit_profession', 'Profit profession'), ('volunteering', 'Volunteering'), ('homemaker', 'Homemaker'), ('retired', 'Retired'), ('other', 'Other')], max_length=32, verbose_name='Current occupation'),
        ),
    ]
