# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:03
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ideascube', '0015_user_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ar_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Arabic knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='camp_activities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Comitees, representation groups'), ('2', 'Music, dance, singing'), ('3', 'Other cultural activities'), ('4', 'Informatic workshops'), ('5', 'Literacy working group'), ('6', 'Talking group'), ('7', 'Recreational'), ('8', 'Volunteering'), ('9', 'Psycosocial'), ('10', 'Educational'), ('11', 'Sport')], max_length=512, verbose_name='Activities in the camp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disabilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('visual', 'Visual'), ('auditive', 'Auditive'), ('physical', 'Physical'), ('cognitive', 'Cognitive'), ('mental', 'Mental')], max_length=128, verbose_name='Disabilities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='en_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='English knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fa_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Persian knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fr_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='French knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ku_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Kurdish knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rn_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Kirundi knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sdb_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Shabak knowledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sw_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('u', 'Understood'), ('w', 'Written'), ('s', 'Spoken'), ('r', 'Read')], max_length=32, verbose_name='Swahili knowledge'),
        ),
    ]
