# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideascube', '0015_user_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=32, verbose_name='Current occupation'),
        ),
    ]
