# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideascube', '0016_auto_20170117_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_level',
            field=models.CharField(blank=True, max_length=32, verbose_name='School level'),
        ),
    ]
