# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_escape_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author_text',
        ),
    ]
