# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_content_author_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='summary'),
        ),
    ]
