#!/bin/bash
NAME=ideascube

case "$1" in
    configure)
        # Create ideascube group if not existing
        if ! getent group "$NAME" > /dev/null 2>&1 ; then
            echo -n "Creating $NAME group..."
            addgroup --quiet --system "$NAME"
            echo " OK"
        fi

        # Create ideascube user if not existing
        if ! id $NAME > /dev/null 2>&1 ; then
            echo -n "Creating $NAME user..."
            adduser --quiet \
                    --system \
                    --no-create-home \
                    --ingroup "$NAME" \
                    --disabled-password \
                    --shell /bin/false \
                    "$NAME"
            echo " OK"
        fi
        chown $NAME:$NAME /var/$NAME
        chown $NAME:$NAME /var/$NAME/main
        echo "Running migration"
        sudo -u $NAME /usr/bin/ideascube migrate --noinput -v 1
        echo "Running collectstatic"
        sudo -u $NAME /usr/bin/ideascube collectstatic --noinput -v 1
        # Nginx
        echo "Linking Nginx VHost"
        ln -fs /etc/nginx/sites-available/$NAME /etc/nginx/sites-enabled/$NAME
        echo "Linking uWSGI app"
        ln -fs /etc/uwsgi/apps-available/$NAME.ini /etc/uwsgi/apps-enabled/$NAME.ini
        echo "Setting permissions on the uWSGI log folder"
        chown -R $NAME:$NAME /var/log/uwsgi
        echo "Restarting Nginx and uWSGI"
        systemctl daemon-reload
        systemctl restart nginx.service uwsgi.service
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        # Do nothing
        ;;
    *)

        echo "Unrecognized postinst argument '$1'"
        ;;
esac

#DEBHELPER#

exit 0
