#!/bin/bash
NAME=ideastube
case "$1" in
    configure)
        echo "Running migration"
        /usr/bin/ideastube migrate --noinput -v 1
        echo "Running collectstatic"
        /usr/bin/ideastube collectstatic --noinput -v 1
        # Nginx
        echo "Installing Nginx VHost"
        ln -fs /etc/nginx/sites-available/$NAME /etc/nginx/sites-enabled/$NAME
        echo "Restarting Nginx"
        service nginx restart
        echo "Make daemon autostart"
        update-rc.d $NAME defaults
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        # Do nothing
        ;;
    *)

        echo "Unrecognized postinst argument '$1'"
        ;;
esac

#DEBHELPER#

exit 0
